### PR TITLE
add: added devops course

### PR DESCRIPTION
**Pull request by 1Shubham7**
I have added one of the most popular courses on DevOps, 

https://www.techworld-with-nana.com/devops-bootcamp. 

Please merge it under Hacktoberfest.

### CODE REVIEW

**Comment by githubber-me** [comment]
This repository only accepts courses which are from the website "educative.io"

**Comment by 1Shubham7** [comment]
ok, got it.

**Comment by 1Shubham7** [comment]
added a devops course from educative.io

**Comment by 1Shubham7** [comment]
Please merge it now.

**Comment by githubber-me** [comment]
The module numbers are 15 as opposed to 53 (which is the number of lessons) you've put here (refer to the table of contents). Change that and create a new pull request, we'll add it !

**Comment by githubber-me** [comment]
*10 is the module number

**Pull request closed without merging**
